services:
  - type: web
    name: event-ticket-booking-backend
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: FIREBASE_TYPE
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_AUTH_URI
        sync: false
      - key: FIREBASE_TOKEN_URI
        sync: false
      - key: FIREBASE_AUTH_PROVIDER_X509_CERT_URL
        sync: false
      - key: FIREBASE_CLIENT_X509_CERT_URL
        sync: false
      - key: FIREBASE_UNIVERSE_DOMAIN
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: APP_ADMIN_EMAILS
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
