server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/internalEventsDB
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

app.auth.admin-emails=${APP_ADMIN_EMAILS:admin@department.edu}
firebase.service-account-path=C:/Users/manoj_tiabzvj/Downloads/depttix-a19c3-firebase-adminsdk-fbsvc-446c4864bd.json

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
